# Generated by Django 5.1.1 on 2024-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_donated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
