# Generated by Django 5.1.1 on 2024-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
